<style type="text/css">
	#servicePanel td {
		line-height: 2em;
	}
	
	#servicePanel span {
		display: block;
		text-align: center;
		font-size: 30px;
		margin: 10px 0px 0px 0px;
	}
	
	#servicePanel p {
		text-align: center;
	}
</style>

<h1>Available services</h1>

<div id="servicePanel" class="nette-inner">
	<table>
	<?php foreach ($list as $namespace => $services): ?>
		<?php if ($namespace != NULL): ?>
		<tr>
			<td colspan="2">
				<span><?php echo htmlspecialchars($namespace) ?></span>
				<p>Accessible via: $container-><?php echo htmlspecialchars($namespace) ?>->service</p>
			</td>
		</tr>
		<?php endif ?>
		<tr>
			<th>Service</th>
			<th>Return</th>
		</tr>
		<?php foreach ($services as $service): ?>
		<tr>
			<td><?php echo htmlspecialchars($service['name']) ?></td>
			<td>
				<?php
					if (isset($service['file'])) {
						echo Nette\Diagnostics\Helpers::editorLink($service['file'], 1)->setText($service['class']);
					} else {
						echo htmlspecialchars($service['class']);
					}
				?>
			</td>
		</tr>
		<?php endforeach ?>
	<?php endforeach ?>
	</table>
</div>